"""Fix part number None issue

Revision ID: 3b1a5c41b24e
Revises: 6128c4c8900c
Create Date: 2025-10-11 13:48:00.201134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1a5c41b24e'
down_revision: Union[str, Sequence[str], None] = '6128c4c8900c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parts', 'part_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_parts_part_number'), table_name='parts')
    op.create_unique_constraint(None, 'parts', ['part_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parts', type_='unique')
    op.create_index(op.f('ix_parts_part_number'), 'parts', ['part_number'], unique=True)
    op.alter_column('parts', 'part_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
