"""Fix part number field for parts table

Revision ID: 6128c4c8900c
Revises: 3d0751137c80
Create Date: 2025-10-11 13:28:22.205010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6128c4c8900c'
down_revision: Union[str, Sequence[str], None] = '3d0751137c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parts', 'part_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(op.f('parts_part_number_key'), 'parts', type_='unique')
    op.create_index(op.f('ix_parts_part_number'), 'parts', ['part_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parts_part_number'), table_name='parts')
    op.create_unique_constraint(op.f('parts_part_number_key'), 'parts', ['part_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('parts', 'part_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
