"""Add locations and inventory tables

Revision ID: 93f0923e97bc
Revises: c9d1fd9d6a43
Create Date: 2025-10-11 11:58:09.271164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f0923e97bc'
down_revision: Union[str, Sequence[str], None] = 'c9d1fd9d6a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventories_id'), 'inventories', ['id'], unique=False)
    op.add_column('parts', sa.Column('part_number', sa.String(length=50), nullable=False))
    op.add_column('parts', sa.Column('manufacturer', sa.String(length=100), nullable=False))
    op.add_column('parts', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('parts', sa.Column('supplier', sa.String(length=100), nullable=False))
    op.add_column('parts', sa.Column('sku', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'parts', ['part_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parts', type_='unique')
    op.drop_column('parts', 'sku')
    op.drop_column('parts', 'supplier')
    op.drop_column('parts', 'category')
    op.drop_column('parts', 'manufacturer')
    op.drop_column('parts', 'part_number')
    op.drop_index(op.f('ix_inventories_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
