"""Add quantity to inventory schema

Revision ID: a62d542621dc
Revises: 3d65ac3427fe
Create Date: 2025-10-13 16:48:30.786720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62d542621dc'
down_revision: Union[str, Sequence[str], None] = '3d65ac3427fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
