"""Add quantity to parts table

Revision ID: c36dfecd65b7
Revises: 3b1a5c41b24e
Create Date: 2025-10-13 13:54:57.429275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36dfecd65b7'
down_revision: Union[str, Sequence[str], None] = '3b1a5c41b24e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'quantity')
    # ### end Alembic commands ###
